build-job:
  tags:
      - debian
  stage: build
  script:
      - poetry build
  artifacts:
      paths:
          - dist/*.whl

test-job:
  tags:
      - debian
  stage: test
  cache:
      paths:
          - tests/images/*.qcow2
  before_script:
      - poetry update
      - poetry install
  script:
      - poetry run pytest

deploy-prod:
  stage: deploy
  tags:
      - debian
  script:
      - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
