build-job:
  tags:
      - debian
  stage: build
  script:
      - poetry build

test-job1:
  tags:
      - debian
  stage: test
  script:
    - poetry run pytest

deploy-prod:
  stage: deploy
  tags:
      - debian
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
