build-job:
  tags:
      - debian
  stage: build
  script:
      - poetry build
  artifacts:
      paths:
          - dist/*.whl

test-job:
  tags:
      - debian
  stage: test
  cache:
      paths:
          # Avoid needing to burn 273 MB of network traffic to grab a new image each time
          - tests/images/*.qcow2
  before_script:
      - poetry update
      - poetry install
      - bash tests/test-machines-up.sh
  script:
      - poetry run pytest
  after_script:
      - bash tests/test-machines-down.sh

deploy-prod:
  stage: deploy
  tags:
      - debian
  script:
      - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
